server:
  port: 8082
user: 
  userServerPath: http://localhost:8081/hello/
spring: 
  application:
    name: chapter10-spring-cloud-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
